version: '3'
services:
  frontend:
    build:
      context: ../
      dockerfile: ./Docker/frontend.Dockerfile
    ports:
      - "8080:80"
    restart: on-failure
    networks:
      - internal_network
    depends_on:
      - openliberty

  openliberty:
    build:
      context: ../
      dockerfile: ./Docker/backend.Dockerfile
    restart: on-failure
    ports:
      - "9080:9080"
    environment:
      - DB_SERVER_NAME=mysql
      - DB_PORT=3306
      - DB_NAME=ssbd02
    networks:
      - internal_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ssbd02
      MYSQL_USER: ssbd02admin
      MYSQL_PASSWORD: dbadmin
      MYSQL_ROOT_PASSWORD: dbadmin
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_REQUIRE_SECURE_TRANSPORT: '0'
    volumes:
      - ../src/main/resources/init-users-mysql.sql:/docker-entrypoint-initdb.d/init-users-mysql.sql
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge