version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ssbd02
      MYSQL_USER: ssbd02admin
      MYSQL_PASSWORD: dbadmin
      MYSQL_ROOT_PASSWORD: dbadmin
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_REQUIRE_SECURE_TRANSPORT: '0'
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d/init-users-mysql.sql:/docker-entrypoint-initdb.d/init-users-mysql.sql

  openliberty:
    image: open-liberty:full
    ports:
      - "9080:9080"
      - "9443:9443"
    restart: always
    depends_on:
      - mysql