package pl.lodz.p.it.ssbd2023.ssbd02.entities.enums;

public enum CategoryName {
  BED, SINGLE_BED, DOUBLE_BED, KIDS, CASE_FURNITURE, WARDROBE, DRESSER, LOCKER, SEAT, CHAIR, DESK,
  STOOL, ARMCHAIR, TABLE, ROUND_TABLE, RECTANGULAR_TABLE
}
