name: Checkstyle

on:
  push:
  workflow_dispatch:

jobs:
  checkstyle:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate
        run: mvn --batch-mode validate
